namespace Aspire.Hosting.ServiceSources.Git;

/// <summary>
/// Writes the files that stop the upward directory walks of MSBuild, NuGet, the .NET SDK host and
/// the compiler's analyzer configuration at the tool-owned <c>.servicesources</c> directory.
/// </summary>
/// <remarks>
/// Checkouts live at <c>&lt;AppHostDirectory&gt;/.servicesources/checkouts/&lt;service&gt;/</c>,
/// which is inside the AppHost's own repository, and every one of those tools finds its settings
/// by walking up from a project or a source file: MSBuild for <c>Directory.Build.props</c>,
/// <c>Directory.Build.targets</c> and <c>Directory.Packages.props</c>, hostfxr and MSBuild for
/// <c>global.json</c>, the compiler for <c>.editorconfig</c>, and NuGet merging every
/// <c>nuget.config</c> from the drive root down. Without a barrier a cloned service is built under
/// the host repository's rules, which were never meant to apply to it. Placing the tool's own
/// copies here ends those walks one directory above the checkouts.
///
/// <para>
/// Every barrier is permissive: each drops a constraint the checkout never opted into, and none
/// adds one. A checkout that brings its own <c>Directory.Build.props</c> (or any of the others) is
/// found first and is unaffected — the barrier only supplies what the checkout does not.
/// </para>
/// <para>
/// <c>nuget.config</c> is the exception to "found first", and the difference bounds what this class
/// can promise. The other four resolvers stop at the nearest file; NuGet merges the whole chain
/// from the drive root down, so a barrier can only override sections it names. It names
/// <c>packageSourceMapping</c>. Everything else in the host repository's config — its
/// <c>packageSources</c>, <c>disabledPackageSources</c>, <c>packageSourceCredentials</c> and
/// <c>config</c> sections — still reaches a checkout, and a host repository that clears
/// <c>packageSources</c> and adds only its own feed therefore still restricts what a checkout can
/// restore. See the README section on checkout isolation, which documents the gap.
/// </para>
/// </remarks>
internal static class CheckoutBuildBarrier
{
    /// <summary>
    /// Set to <c>1</c> or <c>true</c> to keep the package source mapping the AppHost's repository,
    /// the user profile and the machine define, at the cost of a checkout whose packages that
    /// mapping does not cover failing to restore. See <see cref="NuGetConfigContent"/> for what the
    /// default trades away. Only this one barrier is suppressed; the other five are unaffected.
    /// </summary>
    internal const string KeepPackageSourceMappingEnvironmentVariable =
        "SERVICESOURCES_KEEP_PACKAGE_SOURCE_MAPPING";

    private const string GeneratedBanner =
        "Generated by KoalaSoft.Aspire.Hosting.ServiceSources. Do not edit — it is rewritten\n" +
        "  whenever its content differs from what this version of the tool writes.";

    /// <summary>
    /// <see cref="GeneratedBanner"/> re-prefixed for a line-comment syntax, so the wording stays
    /// single-sourced across the XML, INI and JSON barriers.
    /// </summary>
    private static string BannerPrefixedWith(string marker) =>
        string.Join("\n", GeneratedBanner.Split('\n').Select(line => $"{marker} {line}".TrimEnd()));

    /// <summary>
    /// Empty on purpose. MSBuild stops walking up at the first <c>Directory.Build.props</c> or
    /// <c>Directory.Build.targets</c> it finds, so an empty one here means a checkout inherits
    /// nothing from the AppHost repository.
    /// </summary>
    private static readonly string DirectoryBuildContent =
        $"""
         <!--
           {GeneratedBanner}

           Empty on purpose: it exists so MSBuild's search for this file ends here rather than
           continuing up into the AppHost's repository, whose build settings are not meant to
           apply to a service checked out under checkouts/.
         -->
         <Project />

         """.ReplaceLineEndings("\n");

    /// <summary>
    /// Ends the walk for <c>Directory.Packages.props</c> and turns central package management off
    /// for checkouts that do not bring their own. A host repository with
    /// <c>ManagePackageVersionsCentrally=true</c> otherwise turns every version pinned on a
    /// <c>PackageReference</c> in the checkout into an NU1008 restore error.
    /// </summary>
    private static readonly string DirectoryPackagesContent =
        $"""
         <!--
           {GeneratedBanner}

           Ends MSBuild's search for this file above the checkouts, and turns central package
           management off for a checkout that does not bring its own Directory.Packages.props.
           Inheriting ManagePackageVersionsCentrally=true from the AppHost's repository makes
           every version pinned on a PackageReference in the checkout an NU1008 restore error.
         -->
         <Project>
           <PropertyGroup>
             <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
           </PropertyGroup>
         </Project>

         """.ReplaceLineEndings("\n");

    /// <summary>
    /// Drops the package source mapping inherited from the AppHost's repository, so a checkout can
    /// restore a package the host's mapping does not cover.
    /// </summary>
    /// <remarks>
    /// <para>
    /// A <c>&lt;clear /&gt;</c> inside <c>&lt;packageSources&gt;</c> in the checkout's own config
    /// does not clear a mapping defined further up, which is what makes this leak survive the
    /// usual defence. It also hides behind a warm <c>~/.nuget/packages</c>: restore succeeds from
    /// the global folder without contacting a source, so the wrong mapping only shows up on a
    /// clean machine or in CI.
    /// </para>
    /// <para>
    /// Unlike the other five, this barrier is not purely permissive, and the difference is worth
    /// stating plainly. Package source mapping is the control that stops an internal package name
    /// resolving from a public feed, and NuGet's <c>&lt;clear /&gt;</c> discards every mapping
    /// accumulated before it — the machine-wide and user-level ones included, not only the AppHost
    /// repository's. Inside a checkout, mapping is therefore off unless the checkout brings its own,
    /// while every inherited source stays reachable. A package that reaches the shared global
    /// packages folder that way is later served from it to restores that do have mapping in force,
    /// including the AppHost's own, because the global folder is not itself subject to mapping.
    /// </para>
    /// <para>
    /// It is written anyway because the alternative is worse for the case this class exists for: a
    /// mapping the checkout was never written against fails its restore outright, with an NU1100
    /// naming a source rather than the inherited rule behind it. Mapping <c>*</c> to the sources
    /// known at write time would keep the control but silently exclude any source a checkout
    /// defines for itself, turning a security trade-off into a broken build. A host that needs the
    /// mapping enforced inside checkouts instead sets
    /// <see cref="KeepPackageSourceMappingEnvironmentVariable"/>, which suppresses this one file
    /// and leaves the other five in place.
    /// </para>
    /// </remarks>
    private static readonly string NuGetConfigContent =
        $"""
         <?xml version="1.0" encoding="utf-8"?>
         <!--
           {GeneratedBanner}

           NuGet merges every nuget.config from the drive root down, so a packageSourceMapping in
           the AppHost's repository would confine a checkout's restores to the host's feeds. The
           clear below drops that inherited mapping so a checkout restores the packages it was
           written against.

           Note what that costs: a clear discards every mapping accumulated before it, including
           the machine-wide and user-level ones, so package source mapping is off inside checkouts
           unless a checkout brings its own — while all inherited sources stay reachable. Set
           SERVICESOURCES_KEEP_PACKAGE_SOURCE_MAPPING=1 to suppress this file and keep the
           inherited mapping in force; the other five barriers are unaffected.
         -->
         <configuration>
           <packageSourceMapping>
             <clear />
           </packageSourceMapping>
         </configuration>

         """.ReplaceLineEndings("\n");

    /// <summary>
    /// Ends <c>.editorconfig</c>'s upward search at the tool-owned directory. This one is not
    /// covered by <see cref="DirectoryBuildContent"/>: analyzer severity set as
    /// <c>dotnet_diagnostic.&lt;id&gt;.severity = error</c> comes from the <c>.editorconfig</c>
    /// itself, not from <c>EnforceCodeStyleInBuild</c> or <c>TreatWarningsAsErrors</c>, so
    /// neutralizing the MSBuild side leaves a host repository's code style raising the checkout's
    /// own analyzers to errors.
    /// </summary>
    /// <remarks>
    /// <c>root = true</c> is the documented terminator for the walk and carries no style of its
    /// own, so each checkout's own <c>.editorconfig</c> — or the compiler's defaults, where it has
    /// none — governs its diagnostics exactly as it would standalone.
    /// </remarks>
    private static readonly string EditorConfigContent =
        $"""
         {BannerPrefixedWith("#")}
         #
         #   root = true ends .editorconfig's search here rather than letting it continue up into
         #   the AppHost's repository, whose code style is not meant to apply to a service checked
         #   out under checkouts/. No style of its own is set below, on purpose: each checkout's
         #   own .editorconfig governs its diagnostics as it would standalone.
         root = true

         """.ReplaceLineEndings("\n");

    /// <summary>
    /// Requests no SDK version at all, which is what no <c>global.json</c> existing anywhere does.
    /// </summary>
    /// <remarks>
    /// <para>
    /// An empty object is the neutral value, and a barrier here therefore does not have to pin an
    /// SDK: hostfxr stops at the first global.json <em>file</em> it finds and does not keep walking
    /// in search of one carrying an <c>sdk</c> section.
    /// </para>
    /// <para>
    /// Note what this does and does not buy, because the two halves of global.json resolve from
    /// different anchors. <c>msbuild-sdks</c> resolves by walking up from the <em>project</em>
    /// directory, so it is stopped outright. <c>sdk.version</c> resolves by walking up from the
    /// <em>current working directory</em>, so it is stopped only for a build or run launched from
    /// inside the checkout — which is the working directory Aspire gives a project resource. A
    /// build launched with the AppHost directory as its working directory still sees the host's
    /// pin. See the README section on checkout isolation.
    /// </para>
    /// <para>
    /// The comment is safe: both readers of this file — hostfxr and MSBuild's own
    /// <c>msbuild-sdks</c> reader — tolerate one, verified against the real toolchain.
    /// </para>
    /// </remarks>
    private static readonly string GlobalJsonContent =
        $$"""
         {
         {{BannerPrefixedWith("  //")}}
           //
           //   Empty on purpose: hostfxr stops at the first global.json file it finds rather than
           //   continuing up into the AppHost's repository, and an empty object requests no SDK
           //   version at all — the same behaviour as no global.json existing anywhere. This also
           //   drops any msbuild-sdks versions pinned by the AppHost's repository.
         }

         """.ReplaceLineEndings("\n");

    /// <param name="SuppressedBy">
    /// The environment variable that turns this barrier off, or <see langword="null"/> for one that
    /// is always written.
    /// </param>
    private readonly record struct BarrierFile(string Name, string Content, string? SuppressedBy = null);

    private static readonly BarrierFile[] BarrierFiles =
    [
        new("Directory.Build.props", DirectoryBuildContent),
        new("Directory.Build.targets", DirectoryBuildContent),
        new("Directory.Packages.props", DirectoryPackagesContent),
        // Lowercase: NuGet's lookup is case-sensitive on Linux and macOS, and this is the spelling
        // it finds on every platform.
        new("nuget.config", NuGetConfigContent, KeepPackageSourceMappingEnvironmentVariable),
        new(".editorconfig", EditorConfigContent),
        new("global.json", GlobalJsonContent),
    ];

    /// <summary>
    /// Brings the barrier files in <paramref name="serviceSourcesDirectory"/> up to date, writing
    /// only the ones that are missing or hold different content.
    /// </summary>
    public static void Ensure(string serviceSourcesDirectory) =>
        Ensure(serviceSourcesDirectory, Environment.GetEnvironmentVariable);

    /// <summary>
    /// Test seam: <paramref name="environment"/> stands in for the process environment, so the
    /// suppression switch can be exercised without mutating process-wide state.
    /// </summary>
    internal static void Ensure(string serviceSourcesDirectory, Func<string, string?> environment)
    {
        foreach (var file in BarrierFiles)
        {
            var path = Path.Combine(serviceSourcesDirectory, file.Name);

            if (file.SuppressedBy is { } variable && Enabled(environment(variable)))
            {
                // A previous run of this AppHost may have written the barrier before the switch was
                // set, and a stale one on disk goes on doing exactly what the switch asks to stop.
                RemoveIfUnmodified(path, file.Content);
                continue;
            }

            WriteIfDifferent(path, file.Content);
        }

        SweepAbandonedScratchFiles(serviceSourcesDirectory);
    }

    internal static bool Enabled(string? value) =>
        value is "1" || string.Equals(value, "true", StringComparison.OrdinalIgnoreCase);

    /// <summary>
    /// Deletes a barrier this tool wrote. Content that differs is left alone: the directory is
    /// tool-owned, but a developer who has edited a file in it has said something about it that
    /// silently deleting the file would throw away.
    /// </summary>
    private static void RemoveIfUnmodified(string path, string content)
    {
        if (!AlreadyHasContent(path, content))
        {
            return;
        }

        try
        {
            File.Delete(path);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            // Best effort, for the same reason writing one is: an inherited package source mapping
            // is not worth failing service resolution over in either direction.
        }
    }

    /// <summary>
    /// Write-if-absent-or-different, rather than the create-once policy <c>.gitignore</c> gets.
    /// That file's content is fixed forever; barrier content can change between versions of this
    /// tool, and "already there, leave it" would strand an existing checkout on a stale copy with
    /// nothing reporting it.
    /// </summary>
    private static void WriteIfDifferent(string path, string content)
    {
        if (AlreadyHasContent(path, content))
        {
            return;
        }

        // Written elsewhere and renamed into place so a reader — MSBuild, NuGet, or a concurrent
        // resolution of another service (Sources.LocalCheckoutPrefetch runs them in parallel) —
        // never observes a half-written file. Unique per attempt: two of these renames racing is
        // fine, since both are moving identical content into the same name.
        var scratch = Path.Combine(
            Path.GetDirectoryName(path)!,
            $".incoming-{Path.GetFileName(path)}-{Guid.NewGuid():N}");

        try
        {
            File.WriteAllText(scratch, content);
            File.Move(scratch, path, overwrite: true);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            // Best effort. A checkout builds without the barrier — it just inherits the host
            // repository's settings — so a read-only directory or a lost race against another
            // AppHost writing the same bytes must not fail service resolution outright.
        }
        finally
        {
            TryDelete(scratch);
        }
    }

    private static bool AlreadyHasContent(string path, string content)
    {
        try
        {
            return File.Exists(path)
                && string.Equals(File.ReadAllText(path), content, StringComparison.Ordinal);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            // Unreadable right now — most likely a concurrent rename over it. Treated as "does not
            // match" so the write below is attempted; that write tolerates failure in turn.
            return false;
        }
    }

    private static void TryDelete(string path)
    {
        try
        {
            File.Delete(path);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            // The rename already consumed it, or it cannot be removed. Nothing depends on it.
        }
    }

    /// <summary>
    /// How long a scratch file must have gone untouched before it is treated as abandoned rather
    /// than in flight. The same reasoning as
    /// <c>LocalGitCheckout.AbandonedScratchAge</c>, which sweeps the equivalent directories: the
    /// window only has to exceed how long a write can plausibly still be running, and a barrier
    /// file is a few hundred bytes.
    /// </summary>
    private static readonly TimeSpan AbandonedScratchAge = TimeSpan.FromHours(24);

    /// <summary>
    /// Removes scratch files left behind by a process killed between the write and the rename.
    /// <see cref="WriteIfDifferent"/> deletes its own in a <c>finally</c>, which a kill does not
    /// run — and Ctrl-C during startup is normal enough here that the clone path sweeps for the
    /// same reason. No resolver matches these names, so they cost only disk, but nothing else
    /// would ever remove them.
    /// </summary>
    private static void SweepAbandonedScratchFiles(string serviceSourcesDirectory)
    {
        try
        {
            foreach (var scratch in Directory.EnumerateFiles(serviceSourcesDirectory, ".incoming-*"))
            {
                try
                {
                    if (DateTime.UtcNow - File.GetLastWriteTimeUtc(scratch) < AbandonedScratchAge)
                    {
                        continue;
                    }

                    File.Delete(scratch);
                }
                catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
                {
                    // Held open, or not ours to delete. Leave it for a later run.
                }
            }
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            // The enumeration itself failed, so there is nothing we can sweep.
        }
    }
}
