namespace Aspire.Hosting.ServiceSources.Git;

/// <summary>
/// Writes the MSBuild and NuGet files that stop those tools' upward directory walk at the
/// tool-owned <c>.servicesources</c> directory.
/// </summary>
/// <remarks>
/// Checkouts live at <c>&lt;AppHostDirectory&gt;/.servicesources/checkouts/&lt;service&gt;/</c>,
/// which is inside the AppHost's own repository. MSBuild resolves <c>Directory.Build.props</c>,
/// <c>Directory.Build.targets</c> and <c>Directory.Packages.props</c> by walking up from each
/// project until it finds one, and NuGet merges every <c>nuget.config</c> from the drive root down
/// — so without a barrier a cloned service is built under the host repository's rules, which were
/// never meant to apply to it. Placing the tool's own copies here ends the MSBuild walk one
/// directory above the checkouts, and drops the inherited package source mapping.
///
/// A checkout that brings its own <c>Directory.Build.props</c> (or any of the others) is found
/// first and is unaffected: the barrier only supplies what the checkout does not.
/// </remarks>
internal static class CheckoutBuildBarrier
{
    private const string GeneratedBanner =
        "Generated by KoalaSoft.Aspire.Hosting.ServiceSources. Do not edit — it is rewritten\n" +
        "  whenever its content differs from what this version of the tool writes.";

    /// <summary>
    /// Empty on purpose. MSBuild stops walking up at the first <c>Directory.Build.props</c> or
    /// <c>Directory.Build.targets</c> it finds, so an empty one here means a checkout inherits
    /// nothing from the AppHost repository.
    /// </summary>
    private static readonly string DirectoryBuildContent =
        $"""
         <!--
           {GeneratedBanner}

           Empty on purpose: it exists so MSBuild's search for this file ends here rather than
           continuing up into the AppHost's repository, whose build settings are not meant to
           apply to a service checked out under checkouts/.
         -->
         <Project />

         """.ReplaceLineEndings("\n");

    /// <summary>
    /// Ends the walk for <c>Directory.Packages.props</c> and turns central package management off
    /// for checkouts that do not bring their own. A host repository with
    /// <c>ManagePackageVersionsCentrally=true</c> otherwise turns every version pinned on a
    /// <c>PackageReference</c> in the checkout into an NU1008 restore error.
    /// </summary>
    private static readonly string DirectoryPackagesContent =
        $"""
         <!--
           {GeneratedBanner}

           Ends MSBuild's search for this file above the checkouts, and turns central package
           management off for a checkout that does not bring its own Directory.Packages.props.
           Inheriting ManagePackageVersionsCentrally=true from the AppHost's repository makes
           every version pinned on a PackageReference in the checkout an NU1008 restore error.
         -->
         <Project>
           <PropertyGroup>
             <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
           </PropertyGroup>
         </Project>

         """.ReplaceLineEndings("\n");

    /// <summary>
    /// Drops the package source mapping inherited from the AppHost's repository. Only the mapping:
    /// clearing it lifts a restriction rather than removing a feed, so the checkout's own
    /// <c>nuget.config</c> governs its sources exactly as it would standalone.
    /// </summary>
    /// <remarks>
    /// A <c>&lt;clear /&gt;</c> inside <c>&lt;packageSources&gt;</c> in the checkout's own config
    /// does not clear a mapping defined further up, which is what makes this leak survive the
    /// usual defence. It also hides behind a warm <c>~/.nuget/packages</c>: restore succeeds from
    /// the global folder without contacting a source, so the wrong mapping only shows up on a
    /// clean machine or in CI.
    /// </remarks>
    private static readonly string NuGetConfigContent =
        $"""
         <?xml version="1.0" encoding="utf-8"?>
         <!--
           {GeneratedBanner}

           NuGet merges every nuget.config from the drive root down, so a packageSourceMapping in
           the AppHost's repository would confine a checkout's restores to the host's feeds. The
           clear below drops that inherited mapping. It removes a restriction, never a source, so
           each checkout's own nuget.config governs its sources as it would standalone.
         -->
         <configuration>
           <packageSourceMapping>
             <clear />
           </packageSourceMapping>
         </configuration>

         """.ReplaceLineEndings("\n");

    private static readonly (string Name, string Content)[] BarrierFiles =
    [
        ("Directory.Build.props", DirectoryBuildContent),
        ("Directory.Build.targets", DirectoryBuildContent),
        ("Directory.Packages.props", DirectoryPackagesContent),
        // Lowercase: NuGet's lookup is case-sensitive on Linux and macOS, and this is the spelling
        // it finds on every platform.
        ("nuget.config", NuGetConfigContent),
    ];

    /// <summary>
    /// Brings the barrier files in <paramref name="serviceSourcesDirectory"/> up to date, writing
    /// only the ones that are missing or hold different content.
    /// </summary>
    public static void Ensure(string serviceSourcesDirectory)
    {
        foreach (var (name, content) in BarrierFiles)
        {
            WriteIfDifferent(Path.Combine(serviceSourcesDirectory, name), content);
        }
    }

    /// <summary>
    /// Write-if-absent-or-different, rather than the create-once policy <c>.gitignore</c> gets.
    /// That file's content is fixed forever; barrier content can change between versions of this
    /// tool, and "already there, leave it" would strand an existing checkout on a stale copy with
    /// nothing reporting it.
    /// </summary>
    private static void WriteIfDifferent(string path, string content)
    {
        if (AlreadyHasContent(path, content))
        {
            return;
        }

        // Written elsewhere and renamed into place so a reader — MSBuild, NuGet, or a concurrent
        // resolution of another service (Sources.LocalCheckoutPrefetch runs them in parallel) —
        // never observes a half-written file. Unique per attempt: two of these renames racing is
        // fine, since both are moving identical content into the same name.
        var scratch = Path.Combine(
            Path.GetDirectoryName(path)!,
            $".incoming-{Path.GetFileName(path)}-{Guid.NewGuid():N}");

        try
        {
            File.WriteAllText(scratch, content);
            File.Move(scratch, path, overwrite: true);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            // Best effort. A checkout builds without the barrier — it just inherits the host
            // repository's settings — so a read-only directory or a lost race against another
            // AppHost writing the same bytes must not fail service resolution outright.
        }
        finally
        {
            TryDelete(scratch);
        }
    }

    private static bool AlreadyHasContent(string path, string content)
    {
        try
        {
            return File.Exists(path)
                && string.Equals(File.ReadAllText(path), content, StringComparison.Ordinal);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            // Unreadable right now — most likely a concurrent rename over it. Treated as "does not
            // match" so the write below is attempted; that write tolerates failure in turn.
            return false;
        }
    }

    private static void TryDelete(string path)
    {
        try
        {
            File.Delete(path);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
        {
            // The rename already consumed it, or it cannot be removed. Nothing depends on it.
        }
    }
}
